// Generated by CoffeeScript 1.10.0
(function() {
  var getIdentity;

  Accounts.registerLoginHandler(function(loginRequest) {
    var fields, identity, options, profileFields, serviceData, whitelisted;
    if (!loginRequest.cordova) {
      return void 0;
    }
    loginRequest = loginRequest.authResponse;
    identity = getIdentity(loginRequest.accessToken);
    serviceData = {
      accessToken: loginRequest.accessToken,
      expiresAt: (+(new Date)) + (1000 * loginRequest.expiresIn)
    };
    whitelisted = ['id', 'email', 'name', 'first_name', 'last_name', 'link', 'username', 'gender', 'locale', 'age_range'];
    fields = _.pick(identity, whitelisted);
    _.extend(serviceData, fields);
    options = {
      profile: {}
    };
    profileFields = _.pick(identity, whitelisted);
    _.extend(options.profile, profileFields);
    return Accounts.updateOrCreateUserFromExternalService("facebook", serviceData, options);
  });

  getIdentity = function(accessToken) {
    var err, error;
    try {
      return HTTP.get("https://graph.facebook.com/me", {
        params: {
          access_token: accessToken
        }
      }).data;
    } catch (error) {
      err = error;
      throw _.extend(new Error("Failed to fetch identity from Facebook. " + err.message), {
        response: err.response
      });
    }
  };

}).call(this);
