// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.startup(function() {
    return Tracker.autorun(function() {
      if (Meteor.userId()) {
        return RocketChat.Notifications.onUser('notification', function(notification) {
          var hasFocus, messageIsInOpenedRoom, openedRoomId, ref;
          openedRoomId = void 0;
          if ((ref = FlowRouter.getRouteName()) === 'channel' || ref === 'group' || ref === 'direct') {
            openedRoomId = Session.get('openedRoom');
          }
          hasFocus = readMessage.isEnable();
          messageIsInOpenedRoom = openedRoomId === notification.payload.rid;
          fireGlobalEvent('notification', {
            notification: notification,
            fromOpenedRoom: messageIsInOpenedRoom,
            hasFocus: hasFocus
          });
          if (!(hasFocus && messageIsInOpenedRoom)) {
            KonchatNotification.newMessage();
            return KonchatNotification.showDesktop(notification);
          }
        });
      }
    });
  });

}).call(this);
