// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 1,
    up: function() {
      return RocketChat.models.Users.find({
        username: {
          $exists: false
        },
        lastLogin: {
          $exists: true
        }
      }).forEach(function(user) {
        var username;
        username = generateSuggestion(user);
        if ((username != null) && username.trim() !== '') {
          return RocketChat.models.Users.setUsername(user._id, username);
        } else {
          return console.log("User without username", JSON.stringify(user, null, ' '));
        }
      });
    }
  });

}).call(this);
