// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 2,
    up: function() {
      return RocketChat.models.Users.find({
        avatarOrigin: {
          $exists: false
        },
        username: {
          $exists: true
        }
      }).forEach(function(user) {
        var avatars, contentType, dataURI, image, ref, rs, service, services, ws;
        avatars = getAvatarSuggestionForUser(user);
        services = Object.keys(avatars);
        if (services.length === 0) {
          return;
        }
        service = services[0];
        console.log(user.username, '->', service);
        dataURI = avatars[service].blob;
        ref = RocketChatFile.dataURIParse(dataURI), image = ref.image, contentType = ref.contentType;
        rs = RocketChatFile.bufferToStream(new Buffer(image, 'base64'));
        ws = RocketChatFileAvatarInstance.createWriteStream(user.username + ".jpg", contentType);
        ws.on('end', Meteor.bindEnvironment(function() {
          return RocketChat.models.Users.setAvatarOrigin(user._id, service);
        }));
        return rs.pipe(ws);
      });
    }
  });

}).call(this);
