// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 10,
    up: function() {

      /*
      		 * Remove duplicated usernames from rooms
       */
      var count;
      count = 0;
      RocketChat.models.Rooms.find({
        'usernames.0': {
          $exists: true
        }
      }, {
        fields: {
          usernames: 1
        }
      }).forEach(function(room) {
        var newUsernames;
        newUsernames = _.uniq(room.usernames);
        if (newUsernames.length !== room.usernames.length) {
          count++;
          return RocketChat.models.Rooms.update({
            _id: room._id
          }, {
            $set: {
              usernames: newUsernames
            }
          });
        }
      });
      return console.log("Removed duplicated usernames from " + count + " rooms");
    }
  });

}).call(this);
