// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 13,
    up: function() {
      RocketChat.models.Users.setAllUsersActive(true);
      return console.log("Set all users as active");
    }
  });

}).call(this);
