// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 14,
    up: function() {
      var i, len, metaKeys, newValue, oldAndNew, oldValue, ref, ref1;
      RocketChat.models.Settings.remove({
        _id: "API_Piwik_URL"
      });
      RocketChat.models.Settings.remove({
        _id: "API_Piwik_ID"
      });
      RocketChat.models.Settings.remove({
        _id: "Message_Edit"
      });
      RocketChat.models.Settings.remove({
        _id: "Message_Delete"
      });
      RocketChat.models.Settings.remove({
        _id: "Message_KeepStatusHistory"
      });
      RocketChat.models.Settings.update({
        _id: "Message_ShowEditedStatus"
      }, {
        $set: {
          type: "boolean",
          value: true
        }
      });
      RocketChat.models.Settings.update({
        _id: "Message_ShowDeletedStatus"
      }, {
        $set: {
          type: "boolean",
          value: false
        }
      });
      metaKeys = [
        {
          'old': 'Meta:language',
          'new': 'Meta_language'
        }, {
          'old': 'Meta:fb:app_id',
          'new': 'Meta_fb_app_id'
        }, {
          'old': 'Meta:robots',
          'new': 'Meta_robots'
        }, {
          'old': 'Meta:google-site-verification',
          'new': 'Meta_google-site-verification'
        }, {
          'old': 'Meta:msvalidate.01',
          'new': 'Meta_msvalidate01'
        }
      ];
      for (i = 0, len = metaKeys.length; i < len; i++) {
        oldAndNew = metaKeys[i];
        oldValue = (ref = RocketChat.models.Settings.findOne({
          _id: oldAndNew.old
        })) != null ? ref.value : void 0;
        newValue = (ref1 = RocketChat.models.Settings.findOne({
          _id: oldAndNew["new"]
        })) != null ? ref1.value : void 0;
        if ((oldValue != null) && (newValue == null)) {
          RocketChat.models.Settings.update({
            _id: oldAndNew["new"]
          }, {
            $set: {
              value: newValue
            }
          });
        }
        RocketChat.models.Settings.remove({
          _id: oldAndNew.old
        });
      }
      return RocketChat.models.Settings.remove({
        _id: "SMTP_Security"
      });
    }
  });

}).call(this);
