// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 17,
    up: function() {
      return RocketChat.models.Messages.tryDropIndex({
        _hidden: 1
      });
    }
  });

}).call(this);
