// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 20,
    up: function() {

      /*
      		 * Migrate existing `rocketchat_uploads` documents to include the room Id
      		 * where the file was uploaded to. The room Id is retrieved from the message
      		 * document created after the file upload.
       */
      var cursorFileMessages, msgOptions, msgQuery;
      msgQuery = {
        rid: {
          $exists: true
        },
        'file._id': {
          $exists: true
        }
      };
      msgOptions = {
        fields: {
          _id: 1,
          rid: 1,
          'file._id': 1
        }
      };
      cursorFileMessages = RocketChat.models.Messages.find(msgQuery, msgOptions);
      if (!cursorFileMessages.count()) {
        return;
      }
      _.each(cursorFileMessages.fetch(), function(msg) {
        var ref;
        return RocketChat.models.Uploads.update({
          _id: msg != null ? (ref = msg.file) != null ? ref._id : void 0 : void 0
        }, {
          $set: {
            rid: msg.rid
          }
        }, {
          $multi: true
        });
      });
      return console.log('Updated rocketchat_uploads documents to include the room Id in which they were sent.');
    }
  });

}).call(this);
