// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 22,
    up: function() {

      /*
      		 * Update message edit field
       */
      RocketChat.models.Messages.upgradeEtsToEditAt();
      return console.log('Updated old messages\' ets edited timestamp to new editedAt timestamp.');
    }
  });

}).call(this);
