// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 23,
    up: function() {
      RocketChat.models.Settings.remove({
        _id: 'Accounts_denyUnverifiedEmails'
      });
      return console.log('Deleting not used setting Accounts_denyUnverifiedEmails');
    }
  });

}).call(this);
