// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 24,
    up: function() {
      return RocketChat.models.Permissions.remove({
        _id: 'access-rocket-permissions'
      });
    }
  });

}).call(this);
