// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 25,
    up: function() {
      return RocketChat.models.Settings.update({
        _id: /Accounts_OAuth_Custom/
      }, {
        $set: {
          persistent: true
        },
        $unset: {
          hidden: true
        }
      }, {
        multi: true
      });
    }
  });

}).call(this);
