// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 26,
    up: function() {
      return RocketChat.models.Messages.update({
        t: 'rm'
      }, {
        $set: {
          mentions: []
        }
      }, {
        multi: true
      });
    }
  });

}).call(this);
