// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 28,
    up: function() {
      return RocketChat.models.Permissions.addRole('view-c-room', 'bot');
    }
  });

}).call(this);
