// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 29,
    up: function() {
      var LDAP_Bind_Search, LDAP_DN, LDAP_TLS, LDAP_Url, ref, ref1, ref2, ref3;
      LDAP_Url = (ref = RocketChat.models.Settings.findOne('LDAP_Url')) != null ? ref.value : void 0;
      LDAP_TLS = (ref1 = RocketChat.models.Settings.findOne('LDAP_TLS')) != null ? ref1.value : void 0;
      LDAP_DN = (ref2 = RocketChat.models.Settings.findOne('LDAP_DN')) != null ? ref2.value : void 0;
      LDAP_Bind_Search = (ref3 = RocketChat.models.Settings.findOne('LDAP_Bind_Search')) != null ? ref3.value : void 0;
      if ((LDAP_Url != null) && LDAP_Url.trim() !== '') {
        LDAP_Url = LDAP_Url.replace(/ldaps?:\/\//i, '');
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Host'
        }, {
          $set: {
            value: LDAP_Url
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
      }
      if (LDAP_TLS === true) {
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Encryption'
        }, {
          $set: {
            value: 'tls'
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
      }
      if ((LDAP_DN != null) && LDAP_DN.trim() !== '') {
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Domain_Base'
        }, {
          $set: {
            value: LDAP_DN
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Username_Field'
        }, {
          $set: {
            value: ''
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Unique_Identifier_Field'
        }, {
          $set: {
            value: ''
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
      }
      if ((LDAP_Bind_Search != null) && LDAP_Bind_Search.trim() !== '') {
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Custom_Domain_Search'
        }, {
          $set: {
            value: LDAP_Bind_Search
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
        RocketChat.models.Settings.upsert({
          _id: 'LDAP_Use_Custom_Domain_Search'
        }, {
          $set: {
            value: true
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
      }
      RocketChat.models.Settings.remove({
        _id: 'LDAP_Url'
      });
      RocketChat.models.Settings.remove({
        _id: 'LDAP_TLS'
      });
      RocketChat.models.Settings.remove({
        _id: 'LDAP_DN'
      });
      return RocketChat.models.Settings.remove({
        _id: 'LDAP_Bind_Search'
      });
    }
  });

}).call(this);
