// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 30,
    up: function() {
      var WebRTC_STUN_Server, WebRTC_TURN_Password, WebRTC_TURN_Server, WebRTC_TURN_Username, ref, ref1, ref2, ref3, servers;
      WebRTC_STUN_Server = (ref = RocketChat.models.Settings.findOne('WebRTC_STUN_Server')) != null ? ref.value : void 0;
      WebRTC_TURN_Server = (ref1 = RocketChat.models.Settings.findOne('WebRTC_TURN_Server')) != null ? ref1.value : void 0;
      WebRTC_TURN_Username = (ref2 = RocketChat.models.Settings.findOne('WebRTC_TURN_Username')) != null ? ref2.value : void 0;
      WebRTC_TURN_Password = (ref3 = RocketChat.models.Settings.findOne('WebRTC_TURN_Password')) != null ? ref3.value : void 0;
      RocketChat.models.Settings.remove({
        _id: 'WebRTC_STUN_Server'
      });
      RocketChat.models.Settings.remove({
        _id: 'WebRTC_TURN_Server'
      });
      RocketChat.models.Settings.remove({
        _id: 'WebRTC_TURN_Username'
      });
      RocketChat.models.Settings.remove({
        _id: 'WebRTC_TURN_Password'
      });
      if (WebRTC_STUN_Server === 'stun:stun.l.google.com:19302' && WebRTC_TURN_Server === 'turn:numb.viagenie.ca:3478' && WebRTC_TURN_Username === 'team@rocket.chat' && WebRTC_TURN_Password === 'demo') {
        return;
      }
      servers = '';
      if (WebRTC_STUN_Server != null) {
        servers += WebRTC_STUN_Server;
      }
      if (WebRTC_TURN_Server != null) {
        servers += ', ';
        if (WebRTC_TURN_Username != null) {
          servers += encodeURIComponent(WebRTC_TURN_Username) + ':' + encodeURIComponent(WebRTC_TURN_Password) + '@';
        }
        servers += WebRTC_TURN_Server;
      }
      if (servers !== '') {
        return RocketChat.models.Settings.upsert({
          _id: 'WebRTC_Servers'
        }, {
          $set: {
            value: servers
          },
          $setOnInsert: {
            createdAt: new Date
          }
        });
      }
    }
  });

}).call(this);
