// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 31,
    up: function() {
      var changes, from, record, results, to;
      changes = {
        API_Analytics: 'GoogleTagManager_id'
      };
      results = [];
      for (from in changes) {
        to = changes[from];
        record = RocketChat.models.Settings.findOne({
          _id: from
        });
        if (record != null) {
          delete record._id;
          RocketChat.models.Settings.upsert({
            _id: to
          }, record);
        }
        results.push(RocketChat.models.Settings.remove({
          _id: from
        }));
      }
      return results;
    }
  });

}).call(this);
