// Generated by CoffeeScript 1.10.0
(function() {
  RocketChat.Migrations.add({
    version: 32,
    up: function() {
      return RocketChat.models.Settings.update({
        '_id': /Accounts_OAuth_Custom_/
      }, {
        $set: {
          'group': 'OAuth'
        }
      }, {
        multi: true
      });
    }
  });

}).call(this);
