// Generated by CoffeeScript 1.10.0
(function() {
  var url;

  url = Npm.require('url');

  RocketChat.Migrations.add({
    version: 36,
    up: function() {
      var e, error, loginHeader, match, requestUrl;
      loginHeader = RocketChat.models.Settings.findOne({
        _id: 'Layout_Login_Header'
      });
      if ((loginHeader != null ? loginHeader.value : void 0) == null) {
        return;
      }
      match = loginHeader.value.match(/<img\ssrc=['"]([^'"]+)/);
      if ((match != null) && match.length === 2) {
        requestUrl = match[1];
        if (requestUrl[0] === '/') {
          requestUrl = url.resolve(Meteor.absoluteUrl(), requestUrl);
        }
        try {
          Meteor.startup(function() {
            return Meteor.setTimeout(function() {
              var result;
              result = HTTP.get(requestUrl, {
                npmRequestOptions: {
                  encoding: 'binary'
                }
              });
              if (result.statusCode === 200) {
                return RocketChat.Assets.setAsset(result.content, result.headers['content-type'], 'logo');
              }
            }, 30000);
          });
        } catch (error) {
          e = error;
          console.log(e);
        }
      }
      return RocketChat.models.Settings.remove({
        _id: 'Layout_Login_Header'
      });
    }
  });

}).call(this);
