// Generated by CoffeeScript 1.10.0
(function() {
  var control;

  if (RocketChat.Migrations.getVersion() !== 0) {
    RocketChat.Migrations.migrateTo('latest');
  } else {
    control = RocketChat.Migrations._getControl();
    control.version = _.last(RocketChat.Migrations._list).version;
    RocketChat.Migrations._setControl(control);
  }

}).call(this);
