// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    leaveRoom: function(rid) {
      if (!Meteor.userId()) {
        return false;
      }
      ChatSubscription.remove({
        rid: rid,
        'u._id': Meteor.userId()
      });
      return ChatRoom.update(rid, {
        $pull: {
          usernames: Meteor.user().username
        }
      });
    }
  });

}).call(this);
