// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    setUserActiveStatus: function(userId, active) {
      Meteor.users.update(userId, {
        $set: {
          active: active
        }
      });
      return true;
    }
  });

}).call(this);
