// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.publish('activeUsers', function() {
    if (!this.userId) {
      return this.ready();
    }
    return RocketChat.models.Users.findUsersNotOffline({
      fields: {
        username: 1,
        status: 1,
        utcOffset: 1
      }
    });
  });

}).call(this);
