// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.publish('channelAutocomplete', function(name) {
    var cursorHandle, hasPermission, options, pub, roomIds;
    if (!this.userId) {
      return this.ready();
    }
    pub = this;
    options = {
      fields: {
        _id: 1,
        name: 1
      },
      limit: 5,
      sort: {
        name: 1
      }
    };
    roomIds = [];
    if (!RocketChat.authz.hasPermission(this.userId, 'view-c-room') && RocketChat.authz.hasPermission(this.userId, 'view-joined-room')) {
      roomIds = _.pluck(RocketChat.models.Subscriptions.findByUserId(this.userId).fetch(), 'rid');
    }
    hasPermission = (function(_this) {
      return function(_id) {
        return RocketChat.authz.hasPermission(_this.userId, 'view-c-room') || (RocketChat.authz.hasPermission(_this.userId, 'view-joined-room') && roomIds.indexOf(_id) !== -1);
      };
    })(this);
    cursorHandle = RocketChat.models.Rooms.findByNameContainingAndTypes(name, ['c'], options).observeChanges({
      added: function(_id, record) {
        if (hasPermission(_id)) {
          return pub.added('channel-autocomplete', _id, record);
        }
      },
      changed: function(_id, record) {
        if (hasPermission(_id)) {
          return pub.changed('channel-autocomplete', _id, record);
        }
      },
      removed: function(_id, record) {
        if (hasPermission(_id)) {
          return pub.removed('channel-autocomplete', _id, record);
        }
      }
    });
    this.ready();
    this.onStop(function() {
      return cursorHandle.stop();
    });
  });

}).call(this);
