// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.publish('filteredUsers', function(filter) {
    var cursorHandle, exp, options, pub;
    if (!this.userId) {
      return this.ready();
    }
    if (!_.isObject(filter)) {
      return this.ready();
    }
    exp = new RegExp(s.escapeRegExp(filter.name), 'i');
    options = {
      fields: {
        username: 1
      },
      sort: {
        username: 1
      },
      limit: 5
    };
    pub = this;
    cursorHandle = RocketChat.models.Users.findByActiveUsersUsernameExcept(exp, filter.except, options).observeChanges({
      added: function(_id, record) {
        return pub.added('filtered-users', _id, record);
      },
      changed: function(_id, record) {
        return pub.changed('filtered-users', _id, record);
      },
      removed: function(_id, record) {
        return pub.removed('filtered-users', _id, record);
      }
    });
    this.ready();
    this.onStop(function() {
      return cursorHandle.stop();
    });
  });

}).call(this);
