// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.publish('room', function(typeName) {
    var name, type;
    if (!this.userId) {
      return this.ready();
    }
    if (typeof typeName !== 'string') {
      return this.ready();
    }
    type = typeName.substr(0, 1);
    name = typeName.substr(1);
    return RocketChat.roomTypes.runPublish(this, type, name);
  });

}).call(this);
