// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    canAccessRoom: function(rid, userId) {
      var room, user;
      check(rid, String);
      check(userId, String);
      user = RocketChat.models.Users.findOneById(userId, {
        fields: {
          username: 1
        }
      });
      if (!(user != null ? user.username : void 0)) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'canAccessRoom'
        });
      }
      if (!rid) {
        throw new Meteor.Error('error-invalid-room', 'Invalid room', {
          method: 'canAccessRoom'
        });
      }
      room = RocketChat.models.Rooms.findOneById(rid);
      if (room) {
        if (RocketChat.authz.canAccessRoom.call(this, room, user)) {
          room.username = user.username;
          return room;
        } else {
          return false;
        }
      } else {
        throw new Meteor.Error('error-invalid-room', 'Invalid room', {
          method: 'canAccessRoom'
        });
      }
    }
  });

}).call(this);
