// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    deleteUser: function(userId) {
      var adminCount, user, userIsAdmin;
      check(userId, String);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', "Invalid user", {
          method: 'deleteUser'
        });
      }
      user = RocketChat.models.Users.findOneById(Meteor.userId());
      if (RocketChat.authz.hasPermission(Meteor.userId(), 'delete-user') !== true) {
        throw new Meteor.Error('error-not-allowed', "Not allowed", {
          method: 'deleteUser'
        });
      }
      user = RocketChat.models.Users.findOneById(userId);
      if (user == null) {
        throw new Meteor.Error('error-invalid-user', "Invalid user", {
          method: 'deleteUser'
        });
      }
      adminCount = Meteor.users.find({
        roles: {
          $in: ['admin']
        }
      }).count();
      userIsAdmin = user.roles.indexOf('admin') > -1;
      if (adminCount === 1 && userIsAdmin) {
        throw new Meteor.Error('error-action-not-allowed', 'Leaving the app without admins is not allowed', {
          method: 'deleteUser',
          action: 'Remove_last_admin'
        });
      }
      RocketChat.deleteUser(userId);
      return true;
    }
  });

}).call(this);
