// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    eraseRoom: function(rid) {
      var fromId, ref, roomType;
      check(rid, String);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'eraseRoom'
        });
      }
      fromId = Meteor.userId();
      roomType = (ref = RocketChat.models.Rooms.findOneById(rid)) != null ? ref.t : void 0;
      if (RocketChat.authz.hasPermission(fromId, "delete-" + roomType, rid)) {
        RocketChat.models.Messages.removeByRoomId(rid);
        RocketChat.models.Subscriptions.removeByRoomId(rid);
        return RocketChat.models.Rooms.removeById(rid);
      } else {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'eraseRoom'
        });
      }
    }
  });

}).call(this);
