// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    getRoomIdByNameOrId: function(rid) {
      var ref, room;
      check(rid, String);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'getRoomIdByNameOrId'
        });
      }
      room = RocketChat.models.Rooms.findOneById(rid) || RocketChat.models.Rooms.findOneByName(rid);
      if (room == null) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'getRoomIdByNameOrId'
        });
      }
      if (room.usernames.indexOf((ref = Meteor.user()) != null ? ref.username : void 0) !== -1) {
        return room._id;
      }
      if (room.t !== 'c' || RocketChat.authz.hasPermission(Meteor.userId(), 'view-c-room') !== true) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'getRoomIdByNameOrId'
        });
      }
      return room._id;
    }
  });

}).call(this);
