// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    getTotalChannels: function() {
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'getTotalChannels'
        });
      }
      return RocketChat.models.Rooms.find({
        t: 'c'
      }).count();
    }
  });

}).call(this);
