// Generated by CoffeeScript 1.10.0
(function() {
  var slug, usernameIsAvaliable;

  slug = function(text) {
    text = slugify(text, '.');
    return text.replace(/[^0-9a-z-_.]/g, '');
  };

  usernameIsAvaliable = function(username) {
    if (username.length < 1) {
      return false;
    }
    if (username === 'all') {
      return false;
    }
    return !RocketChat.models.Users.findOneByUsername({
      $regex: new RegExp("^" + username + "$", "i")
    });
  };

  this.generateSuggestion = function(user) {
    var email, first, i, index, item, j, k, last, len, len1, len2, nameParts, ref, ref1, ref2, ref3, ref4, ref5, service, serviceName, username, usernames;
    usernames = [];
    username = void 0;
    if (Meteor.settings["public"].sandstorm) {
      usernames.push(user.services.sandstorm.preferredHandle);
    }
    if (RocketChat.settings.get('UTF8_Names_Slugify')) {
      usernames.push(slug(user.name));
    } else {
      usernames.push(user.name);
    }
    nameParts = user != null ? (ref = user.name) != null ? ref.split(' ') : void 0 : void 0;
    if (nameParts.length > 1) {
      first = nameParts[0];
      last = nameParts[nameParts.length - 1];
      if (RocketChat.settings.get('UTF8_Names_Slugify')) {
        usernames.push(slug(first[0] + last));
        usernames.push(slug(first + last[0]));
      } else {
        usernames.push(first[0] + last);
        usernames.push(first + last[0]);
      }
    }
    if (((ref1 = user.profile) != null ? ref1.name : void 0) != null) {
      if (RocketChat.settings.get('UTF8_Names_Slugify')) {
        usernames.push(slug(user.profile.name));
      } else {
        usernames.push(user.profile.name);
      }
    }
    if (user.services != null) {
      ref2 = user.services;
      for (serviceName in ref2) {
        service = ref2[serviceName];
        if (service.name != null) {
          if (RocketChat.settings.get('UTF8_Names_Slugify')) {
            usernames.push(slug(service.name));
          } else {
            usernames.push(service.name);
          }
        } else if (service.username != null) {
          if (RocketChat.settings.get('UTF8_Names_Slugify')) {
            usernames.push(slug(service.username));
          } else {
            usernames.push(service.username);
          }
        }
      }
    }
    if (((ref3 = user.emails) != null ? ref3.length : void 0) > 0) {
      ref4 = user.emails;
      for (i = 0, len = ref4.length; i < len; i++) {
        email = ref4[i];
        if ((email.address != null) && email.verified === true) {
          usernames.push(slug(email.address.replace(/@.+$/, '')));
        }
      }
      ref5 = user.emails;
      for (j = 0, len1 = ref5.length; j < len1; j++) {
        email = ref5[j];
        if ((email.address != null) && email.verified === true) {
          usernames.push(slug(email.address.replace(/(.+)@(\w+).+/, '$1.$2')));
        }
      }
    }
    for (k = 0, len2 = usernames.length; k < len2; k++) {
      item = usernames[k];
      if (usernameIsAvaliable(item)) {
        username = item;
        break;
      }
    }
    if ((usernames[0] != null) && usernames[0].length > 0) {
      index = 0;
      while (username == null) {
        index++;
        if (usernameIsAvaliable(usernames[0] + '-' + index)) {
          username = usernames[0] + '-' + index;
        }
      }
    }
    if (usernameIsAvaliable(username)) {
      return username;
    }
    return void 0;
  };

  RocketChat.generateUsernameSuggestion = generateSuggestion;

  Meteor.methods({
    getUsernameSuggestion: function() {
      var user;
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'getUsernameSuggestion'
        });
      }
      user = Meteor.user();
      return generateSuggestion(user);
    }
  });

}).call(this);
