// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    loadLocale: function(locale) {
      var e, error;
      check(locale, String);
      try {
        return Assets.getText("moment-locales/" + (locale.toLowerCase()) + ".js");
      } catch (error) {
        e = error;
        return console.log(e);
      }
    }
  });

}).call(this);
