// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    loadNextMessages: function(rid, end, limit) {
      var fromId, messages, options, records;
      if (limit == null) {
        limit = 20;
      }
      check(rid, String);
      check(limt, Number);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'loadNextMessages'
        });
      }
      fromId = Meteor.userId();
      if (!Meteor.call('canAccessRoom', rid, fromId)) {
        return false;
      }
      options = {
        sort: {
          ts: 1
        },
        limit: limit
      };
      if (!RocketChat.settings.get('Message_ShowEditedStatus')) {
        options.fields = {
          'editedAt': 0
        };
      }
      if (end != null) {
        records = RocketChat.models.Messages.findVisibleByRoomIdAfterTimestamp(rid, end, options).fetch();
      } else {
        records = RocketChat.models.Messages.findVisibleByRoomId(rid, options).fetch();
      }
      messages = _.map(records, function(message) {
        message.starred = _.findWhere(message.starred, {
          _id: fromId
        });
        return message;
      });
      return {
        messages: messages
      };
    }
  });

}).call(this);
