// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    logoutCleanUp: function(user) {
      check(user, Object);
      return Meteor.defer(function() {
        return RocketChat.callbacks.run('afterLogoutCleanUp', user);
      });
    }
  });

}).call(this);
