// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    migrateTo: function(version) {
      var user;
      check(version, String);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'migrateTo'
        });
      }
      user = Meteor.user();
      if ((user == null) || RocketChat.authz.hasPermission(user._id, 'run-migration') !== true) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'migrateTo'
        });
      }
      this.unblock();
      RocketChat.Migrations.migrateTo(version);
      return version;
    },
    getMigrationVersion: function() {
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'getMigrationVersion'
        });
      }
      return RocketChat.Migrations.getVersion();
    }
  });

}).call(this);
