// Generated by CoffeeScript 1.10.0
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Meteor.methods({
    muteUserInRoom: function(data) {
      var fromId, fromUser, mutedUser, ref, ref1, room;
      check(data, Match.ObjectIncluding({
        rid: String,
        username: String
      }));
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'muteUserInRoom'
        });
      }
      fromId = Meteor.userId();
      if (!RocketChat.authz.hasPermission(fromId, 'mute-user', data.rid)) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'muteUserInRoom'
        });
      }
      room = RocketChat.models.Rooms.findOneById(data.rid);
      if (!room) {
        throw new Meteor.Error('error-invalid-room', 'Invalid room', {
          method: 'muteUserInRoom'
        });
      }
      if ((ref = room.t) !== 'c' && ref !== 'p') {
        throw new Meteor.Error('error-invalid-room-type', room.t + ' is not a valid room type', {
          method: 'muteUserInRoom',
          type: room.t
        });
      }
      if (ref1 = data.username, indexOf.call((room != null ? room.usernames : void 0) || [], ref1) < 0) {
        throw new Meteor.Error('error-user-not-in-room', 'User is not in this room', {
          method: 'muteUserInRoom'
        });
      }
      mutedUser = RocketChat.models.Users.findOneByUsername(data.username);
      RocketChat.models.Rooms.muteUsernameByRoomId(data.rid, mutedUser.username);
      fromUser = RocketChat.models.Users.findOneById(fromId);
      RocketChat.models.Messages.createUserMutedWithRoomIdAndUser(data.rid, mutedUser, {
        u: {
          _id: fromUser._id,
          username: fromUser.username
        }
      });
      return true;
    }
  });

}).call(this);
