// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    saveUserPreferences: function(settings) {
      var preferences;
      check(settings, Object);
      if (Meteor.userId()) {
        preferences = {};
        if (settings.language != null) {
          RocketChat.models.Users.setLanguage(Meteor.userId(), settings.language);
        }
        if (settings.newRoomNotification != null) {
          preferences.newRoomNotification = settings.newRoomNotification === "1" ? true : false;
        }
        if (settings.newMessageNotification != null) {
          preferences.newMessageNotification = settings.newMessageNotification === "1" ? true : false;
        }
        if (settings.useEmojis != null) {
          preferences.useEmojis = settings.useEmojis === "1" ? true : false;
        }
        if (settings.convertAsciiEmoji != null) {
          preferences.convertAsciiEmoji = settings.convertAsciiEmoji === "1" ? true : false;
        }
        if (settings.saveMobileBandwidth != null) {
          preferences.saveMobileBandwidth = settings.saveMobileBandwidth === "1" ? true : false;
        }
        if (settings.collapseMediaByDefault != null) {
          preferences.collapseMediaByDefault = settings.collapseMediaByDefault === "1" ? true : false;
        }
        if (settings.unreadRoomsMode != null) {
          preferences.unreadRoomsMode = settings.unreadRoomsMode === "1" ? true : false;
        }
        if (settings.autoImageLoad != null) {
          preferences.autoImageLoad = settings.autoImageLoad === "1" ? true : false;
        }
        if (settings.emailNotificationMode != null) {
          preferences.emailNotificationMode = settings.emailNotificationMode;
        }
        if (settings.mergeChannels !== "-1") {
          preferences.mergeChannels = settings.mergeChannels === "1";
        } else {
          delete preferences.mergeChannels;
        }
        if (settings.unreadAlert != null) {
          preferences.unreadAlert = settings.unreadAlert === "1" ? true : false;
        }
        preferences.desktopNotificationDuration = settings.desktopNotificationDuration - 0;
        preferences.viewMode = settings.viewMode || 0;
        preferences.hideUsernames = settings.hideUsernames === "1";
        preferences.hideAvatars = settings.hideAvatars === "1";
        preferences.hideFlexTab = settings.hideFlexTab === "1";
        preferences.highlights = settings.highlights;
        RocketChat.models.Users.setPreferences(Meteor.userId(), preferences);
        return true;
      }
    }
  });

}).call(this);
