// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    sendForgotPasswordEmail: function(email) {
      var regex, user;
      check(email, String);
      email = s.trim(email);
      user = RocketChat.models.Users.findOneByEmailAddress(email);
      if (user != null) {
        regex = new RegExp("^" + s.escapeRegExp(email) + "$", 'i');
        email = _.find(_.pluck(user.emails || [], 'address'), function(userEmail) {
          return regex.test(userEmail);
        });
        Accounts.sendResetPasswordEmail(user._id, email);
        return true;
      }
      return false;
    }
  });

}).call(this);
