// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    setUserPassword: function(password) {
      var user;
      check(password, String);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'setUserPassword'
        });
      }
      user = RocketChat.models.Users.findOneById(Meteor.userId());
      if (user && user.requirePasswordChange !== true) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'setUserPassword'
        });
      }
      Accounts.setPassword(Meteor.userId(), password, {
        logout: false
      });
      return RocketChat.models.Users.unsetRequirePasswordChange(Meteor.userId());
      return true;
    }
  });

}).call(this);
