// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    setUserActiveStatus: function(userId, active) {
      check(userId, String);
      check(active, Boolean);
      if (!Meteor.userId()) {
        throw new Meteor.Error('error-invalid-user', 'Invalid user', {
          method: 'setUserActiveStatus'
        });
      }
      if (RocketChat.authz.hasPermission(Meteor.userId(), 'edit-other-user-active-status') !== true) {
        throw new Meteor.Error('error-not-allowed', 'Not allowed', {
          method: 'setUserActiveStatus'
        });
      }
      RocketChat.models.Users.setUserActive(userId, active);
      if (active === false) {
        RocketChat.models.Users.unsetLoginTokens(userId);
      }
      return true;
    }
  });

}).call(this);
