// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.methods({
    userSetUtcOffset: function(utcOffset) {
      check(utcOffset, Number);
      if (this.userId == null) {
        return;
      }
      this.unblock();
      return RocketChat.models.Users.setUtcOffset(this.userId, utcOffset);
    }
  });

  DDPRateLimiter.addRule({
    type: 'method',
    name: 'userSetUtcOffset',
    userId: function() {
      return true;
    }
  }, 1, 60000);

}).call(this);
