// Generated by CoffeeScript 1.10.0
(function() {
  var mixin;

  mixin = function(obj) {
    return _.each(_.functions(obj), function(name) {
      var func;
      if (!_[name] && (_.prototype[name] == null)) {
        func = _[name] = obj[name];
        return _.prototype[name] = function() {
          var args;
          args = [this._wrapped];
          push.apply(args, arguments);
          return result.call(this, func.apply(_, args));
        };
      }
    });
  };

  mixin(s.exports());

}).call(this);
