// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.startup(function() {
    return Tracker.autorun(function() {
      var hasFocus, i, len, openedRoomId, ref, ref1, ref2, ref3, subscription, subscriptionIsTheOpenedRoom, subscriptions, unreadAlert, unreadCount;
      unreadCount = 0;
      unreadAlert = false;
      subscriptions = ChatSubscription.find({
        open: true
      }, {
        fields: {
          unread: 1,
          alert: 1,
          rid: 1,
          t: 1,
          name: 1,
          ls: 1,
          unreadAlert: 1
        }
      });
      openedRoomId = void 0;
      Tracker.nonreactive(function() {
        var ref;
        if ((ref = FlowRouter.getRouteName()) === 'channel' || ref === 'group' || ref === 'direct') {
          return openedRoomId = Session.get('openedRoom');
        }
      });
      ref = subscriptions.fetch();
      for (i = 0, len = ref.length; i < len; i++) {
        subscription = ref[i];
        fireGlobalEvent('unread-changed-by-subscription', subscription);
        if (subscription.alert || subscription.unread > 0) {
          hasFocus = readMessage.isEnable();
          subscriptionIsTheOpenedRoom = openedRoomId === subscription.rid;
          if (hasFocus && subscriptionIsTheOpenedRoom) {
            Meteor.setTimeout(function() {
              return readMessage.readNow();
            }, 500);
          }
          unreadCount += subscription.unread;
          if (subscription.alert === true && subscription.unreadAlert !== 'nothing') {
            if (subscription.unreadAlert === 'all' || ((ref1 = Meteor.user()) != null ? (ref2 = ref1.settings) != null ? (ref3 = ref2.preferences) != null ? ref3.unreadAlert : void 0 : void 0 : void 0) !== false) {
              unreadAlert = '•';
            }
          }
        }
        if (RoomManager.openedRooms[subscription.t + subscription.name]) {
          readMessage.refreshUnreadMark(subscription.rid);
        }
      }
      menu.updateUnreadBars();
      if (unreadCount > 0) {
        if (unreadCount > 999) {
          return Session.set('unread', '999+');
        } else {
          return Session.set('unread', unreadCount);
        }
      } else if (unreadAlert !== false) {
        return Session.set('unread', unreadAlert);
      } else {
        return Session.set('unread', '');
      }
    });
  });

  Meteor.startup(function() {
    window.favico = new Favico({
      position: 'up',
      animation: 'none'
    });
    return Tracker.autorun(function() {
      var siteName, unread;
      siteName = RocketChat.settings.get('Site_Name') || '';
      unread = Session.get('unread');
      fireGlobalEvent('unread-changed', unread);
      if (typeof favico !== "undefined" && favico !== null) {
        favico.badge(unread, {
          bgColor: typeof unread !== 'number' ? '#3d8a3a' : '#ac1b1b'
        });
      }
      return document.title = unread === '' ? siteName : '(' + unread + ') ' + siteName;
    });
  });

}).call(this);
