// Generated by CoffeeScript 1.10.0
(function() {
  var ref;

  if ((ref = Meteor.AppCache) != null) {
    ref.config({
      onlineOnly: ['/elements/', '/landing/', '/moment-locales/', '/scripts/']
    });
  }

}).call(this);
