// Generated by CoffeeScript 1.10.0
(function() {
  var generateStatistics, logger;

  logger = new Logger('SyncedCron');

  SyncedCron.config({
    logger: function(opts) {
      return logger[opts.level].call(logger, opts.message);
    },
    collectionName: 'rocketchat_cron_history'
  });

  generateStatistics = function() {
    var e, error, statistics;
    statistics = RocketChat.statistics.save();
    statistics.host = Meteor.absoluteUrl();
    if (RocketChat.settings.get('Statistics_reporting')) {
      try {
        HTTP.post('https://collector.rocket.chat/', {
          data: statistics
        });
      } catch (error) {
        e = error;
        logger.warn('Failed to send usage report');
      }
    }
  };

  Meteor.startup(function() {
    return Meteor.defer(function() {
      generateStatistics();
      SyncedCron.add({
        name: 'Generate and save statistics',
        schedule: function(parser) {
          return parser.text('every 1 hour');
        },
        job: generateStatistics
      });
      return SyncedCron.start();
    });
  });

}).call(this);
