// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.startup(function() {
    var instance;
    instance = {
      host: 'localhost',
      port: process.env.PORT
    };
    if (process.env.INSTANCE_IP) {
      instance.host = process.env.INSTANCE_IP;
    }
    InstanceStatus.registerInstance('rocket.chat', instance);
    UserPresence.start();
    return UserPresenceMonitor.start();
  });

}).call(this);
